### ISSUE TITLE
Source files doesn't exist 

### ISSUE THREAD

**Issue by praduca** [bosh77/MsxCompilerV4#1]
There is no source on the zip and gzip files, just the license and readme files

**Comment by bosh77** [comment]
Go to the Download section

https://github.com/bosh77/MsxCompilerV4/releases/tag/MSXv4

**Comment by praduca** [comment]
Hi
I did, the files named source have only 2 files inside, readme.md and license

**Comment by bosh77** [comment]
go to release section, you can see the files .zip

[MSXcompilerV4win.zip](https://github.com/bosh77/MsxCompilerV4/releases/download/MSXv4/MSXcompilerV4win.zip)
[MSXcompilerV4macos.zip](https://github.com/bosh77/MsxCompilerV4/releases/download/MSXv4/MSXcompilerV4macos.zip)

If you mean the source files then they are not included

**Comment by praduca** [comment]
Hi
I saw those, what i mean is that the source code zip files have no source inside
the release files also dont have the source

**Comment by bosh77** [comment]
source files are not included in the project, sorry

**Comment by praduca** [comment]
ok but you stated that the project is gpl? well i'm closing this then
