### ISSUE TITLE
Application does not start on MAC OS Monterey

### ISSUE THREAD

**Issue by Neurox66** [bosh77/MsxCompilerV4#2]
Hi,
When I run the application MSXCompilerV4.app, the operating system returns the following error
<img width="303" alt="MSXCompilerV4_errore" src="https://user-images.githubusercontent.com/69666401/221400417-1189537f-0994-47c4-af09-ace32a744a57.png">
I have tried several times but it always returns the same problem. The MAC OS version is 12.6.2 (21G320)
Regards,
Paolo

**Comment by bosh77** [comment]
try at this link

https://cfpmanfredini.wordpress.com/2021/09/24/e-danneggiato-e-non-puo-essere-aperto-dovresti-spostarlo-nel-cestino/

in the terminal type this: 

sudo xattr -cr

followed by the path and application name

let me know if it works

Daniele

**Comment by Neurox66** [comment]
Ciao Daniele,
thanks for the hints.
Now running very well.
Paolo
